#!/bin/sh -ex

cd /golf/local
mkdir -p gobin
hg clone -r release https://go.googlecode.com/hg/ go
cd go/src
PATH=/golf/local/gobin:$PATH GOBIN=/golf/local/gobin GOARCH=386 GOOS=linux GOROOT=/golf/local/go ./all.bash
