TARGETS = \
srv/local/dmd2/bin/dmd \
srv/local/dmd/linux/bin/dmd \
/usr/local/bin/goruby-1.9 \
/golf/local/j601 \
/usr/local/bin/xgawk \
/usr/local/bin/cyc \

#srv/local/dmd2/linux/bin/dmd \

all: $(TARGETS)

#srv/local/dmd2/linux/bin/dmd:
srv/local/dmd2/bin/dmd:
	fetcher/d2

srv/local/dmd/linux/bin/dmd:
	fetcher/d

/usr/local/bin/goruby-1.9:
	fetcher/grb

/golf/local/j601:
	fetcher/j

/usr/local/bin/xgawk:
	fetcher/xgawk

/usr/local/bin/cyc:
	fetcher/curry

